// Calendar mutations types
const SET_SELECTED_DAY = 'SET_SELECTED_DAY';
const SET_TODAY = 'SET_TODAY';
const SET_CALENDAR = 'SET_CALENDAR';

// Events mutations types
const ADD_EVENT = 'ADD_EVENT';
const SHOW_FORM = 'SHOW_FORM';
const CLOSE_FORM = 'CLOSE_FORM';
const DELETE_EVENT = 'DELETE_EVENT';
const SET_NOTIFICATION_TIME = 'SET_NOTIFICATION_TIME';
const GRANT_NOTIFICATION = 'GRANT_NOTIFICATION';

export default {
  SET_SELECTED_DAY,
  SET_TODAY,
  SET_CALENDAR,

  ADD_EVENT,
  SHOW_FORM,
  CLOSE_FORM,
  DELETE_EVENT,
  SET_NOTIFICATION_TIME,
  GRANT_NOTIFICATION,
};
